-- Catálogo de clasificación de conceptos SATQ: programa y tipo de acto.
-- Generado por clasificación automática (regex sobre el texto del concepto),
-- revisable/editable a futuro sin tocar código. Ver análisis en el chat.

CREATE TABLE satq_catalogo_conceptos (
    id_concepto     INTEGER PRIMARY KEY,
    programa        VARCHAR(40) NOT NULL DEFAULT 'Regular',
    tipo_acto       VARCHAR(60) NOT NULL DEFAULT 'Sin clasificar',
    es_subsidio     BOOLEAN NOT NULL DEFAULT false,
    actualizado_en  TIMESTAMP DEFAULT now()
);

INSERT INTO satq_catalogo_conceptos (id_concepto, programa, tipo_acto, es_subsidio) VALUES
(12, 'INFONAVIT/FOVISSSTE', 'Acto/contrato traslativo de dominio', false),
(58, 'Regular', 'Aviso preventivo', true),
(61, 'Regular', 'Anotaciones / rectificación', true),
(83, 'INFONAVIT/FOVISSSTE', 'Acto/contrato traslativo de dominio', true),
(132, 'Regular', 'Análisis y calificación', false),
(135, 'Regular', 'Análisis y calificación', false),
(136, 'Regular', 'Fojas y anexos', false),
(137, 'Regular', 'Aviso preventivo', false),
(140, 'Regular', 'Certificados / constancias', false),
(141, 'Regular', 'Certificados / constancias', false),
(143, 'Regular', 'Certificados / constancias', false),
(144, 'Regular', 'Certificados / constancias', false),
(145, 'Regular', 'Testamentos', false),
(146, 'Regular', 'Testamentos', false),
(148, 'Regular', 'Certificados / constancias', false),
(149, 'Regular', 'Análisis y calificación', false),
(150, 'Regular', 'Cancelación de aviso preventivo', false),
(156, 'SEDETUS', 'Análisis y calificación', false),
(157, 'SEDETUS', 'Análisis y calificación', true),
(160, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(161, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', true),
(162, 'INFONAVIT/FOVISSSTE', 'Cancelación de crédito hipotecario', false),
(163, 'INFONAVIT/FOVISSSTE', 'Cancelación de crédito hipotecario', true),
(164, 'INSUS', 'Acto/contrato traslativo de dominio', false),
(165, 'INSUS', 'Acto/contrato traslativo de dominio', true),
(166, 'INSUS', 'Cancelación de reserva de dominio', false),
(167, 'INSUS', 'Cancelación de reserva de dominio', true),
(168, 'INSUS', 'Subdivisión / fusión de predios', false),
(169, 'INSUS', 'Subdivisión / fusión de predios', true),
(172, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(173, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', true),
(174, 'INSUS', 'Fojas y anexos', false),
(175, 'INSUS', 'Fojas y anexos', true),
(176, 'SEDETUS', 'Fojas y anexos', false),
(177, 'SEDETUS', 'Fojas y anexos', true),
(178, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(179, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', true),
(182, 'INSUS', 'Anotaciones / rectificación', false),
(184, 'SEDETUS', 'Anotaciones / rectificación', false),
(185, 'SEDETUS', 'Anotaciones / rectificación', true),
(203, 'Regular', 'Análisis y calificación', true),
(204, 'Regular', 'Fojas y anexos', false),
(206, 'Regular', 'Diferencia por cambio de U.M.A.', false),
(229, 'Regular', 'Sin clasificar', true),
(245, 'Regular', 'Testamentos', false),
(246, 'Regular', 'Sin clasificar', false),
(247, 'Regular', 'Certificados / constancias', true),
(249, 'Regular', 'Acto/contrato traslativo de dominio', false),
(250, 'Regular', 'Cancelación de reserva de dominio', false),
(251, 'Regular', 'Anotaciones / rectificación', false),
(252, 'Regular', 'Cancelación de reserva de dominio', false),
(253, 'Regular', 'Acto/contrato traslativo de dominio', false),
(254, 'Regular', 'Fojas y anexos', false),
(255, 'Regular', 'Anotaciones / rectificación', false),
(256, 'Regular', 'Acto/contrato traslativo de dominio', true),
(258, 'Regular', 'Anotaciones / rectificación', true),
(259, 'Regular', 'Cancelación de reserva de dominio', true),
(261, 'Regular', 'Anotaciones / rectificación', true),
(262, 'Regular', 'Anotaciones / rectificación', true),
(263, 'AGEPROO', 'Análisis y calificación', false),
(264, 'AGEPROO', 'Análisis y calificación', false),
(267, 'AGEPROO', 'Certificados / constancias', false),
(268, 'AGEPROO', 'Certificados / constancias', false),
(269, 'AGEPROO', 'Análisis y calificación', false),
(270, 'AGEPROO', 'Sin clasificar', true),
(271, 'AGEPROO', 'Sin clasificar', true),
(276, 'AGEPROO', 'Anotaciones / rectificación', true),
(278, 'AGEPROO', 'Cancelación de aviso preventivo', false),
(296, 'Regular', 'Cancelación de reserva de dominio', false),
(297, 'Regular', 'Cancelación de reserva de dominio', true),
(300, 'Regular', 'Cancelación de reserva de dominio', false),
(301, 'Regular', 'Cancelación de reserva de dominio', true),
(304, 'Regular', 'Aviso preventivo', false),
(305, 'Regular', 'Sin clasificar', true),
(306, 'Regular', 'Certificados / constancias', false),
(307, 'Regular', 'Certificados / constancias', true),
(308, 'Regular', 'Certificados / constancias', false),
(309, 'Regular', 'Certificados / constancias', true),
(310, 'Regular', 'Certificados / constancias', false),
(311, 'Regular', 'Certificados / constancias', true),
(312, 'Regular', 'Certificados / constancias', false),
(313, 'Regular', 'Certificados / constancias', true),
(318, 'Regular', 'Análisis y calificación', false),
(321, 'Regular', 'Aviso preventivo', false),
(323, 'Regular', 'Certificados / constancias', false),
(324, 'Regular', 'Cancelación de aviso preventivo', false),
(325, 'Regular', 'Análisis y calificación', true),
(328, 'Regular', 'Aviso preventivo', true),
(330, 'Regular', 'Certificados / constancias', true),
(331, 'Regular', 'Cancelación de aviso preventivo', true),
(333, 'Regular', 'Régimen de condominio', false),
(335, 'Regular', 'Otorgamiento de crédito hipotecario', false),
(336, 'Regular', 'Inscripción de gravamen/garantía', false),
(339, 'Regular', 'Régimen de condominio', true),
(341, 'Regular', 'Otorgamiento de crédito hipotecario', true),
(342, 'Regular', 'Inscripción de gravamen/garantía', true),
(346, 'Regular', 'Análisis y calificación', false),
(353, 'Regular', 'Análisis y calificación', false),
(360, 'Regular', 'Cancelación de reserva de dominio', false),
(363, 'Regular', 'Cancelación de reserva de dominio', false),
(364, 'Regular', 'Fojas y anexos', false),
(366, 'Regular', 'Anotaciones / rectificación', false),
(368, 'Regular', 'Cancelación de reserva de dominio', true),
(370, 'Regular', 'Inscripción de gravamen/garantía', false),
(371, 'Regular', 'Fojas y anexos', true),
(373, 'Regular', 'Anotaciones / rectificación', true),
(374, 'INFONAVIT/FOVISSSTE', 'Acto/contrato traslativo de dominio', false),
(375, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(376, 'INFONAVIT/FOVISSSTE', 'Cancelación de crédito hipotecario', false),
(377, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(378, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(379, 'INFONAVIT/FOVISSSTE', 'Acto/contrato traslativo de dominio', true),
(380, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', true),
(381, 'INFONAVIT/FOVISSSTE', 'Cancelación de crédito hipotecario', true),
(382, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', true),
(383, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', true),
(390, 'Regular', 'Sin clasificar', false),
(391, 'Regular', 'Servicios registrales (alertas/altas)', false),
(392, 'Regular', 'Servicios registrales (alertas/altas)', false),
(393, 'Regular', 'Servicios registrales (alertas/altas)', false),
(394, 'Regular', 'Certificados / constancias', false),
(396, 'Regular', 'Certificados / constancias', false),
(398, 'Regular', 'Certificados / constancias', false),
(399, 'Regular', 'Análisis y calificación', false),
(400, 'Regular', 'Anotaciones / rectificación', false),
(401, 'Regular', 'Fojas y anexos', false),
(402, 'Regular', 'Fojas y anexos', false),
(406, 'Regular', 'Análisis y calificación', false),
(407, 'Regular', 'Certificados / constancias', true),
(408, 'Regular', 'Certificados / constancias', true),
(409, 'Regular', 'Acto/contrato traslativo de dominio', false),
(410, 'Regular', 'Aviso preventivo', false),
(411, 'Regular', 'Aviso preventivo', false),
(413, 'Regular', 'Acto/contrato traslativo de dominio', true),
(414, 'Regular', 'Aviso preventivo', true),
(415, 'Regular', 'Aviso preventivo', true),
(417, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(418, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(419, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', true),
(420, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', true),
(421, 'Regular', 'Inscripción de gravamen/garantía', false),
(422, 'Regular', 'Inscripción de gravamen/garantía', false),
(427, 'Regular', 'Análisis y calificación', true),
(435, 'SEDETUS', 'Certificados / constancias', false),
(436, 'SEDETUS', 'Certificados / constancias', true),
(438, 'Regular', 'Certificados / constancias', true),
(439, 'INSUS', 'Certificados / constancias', false),
(440, 'INSUS', 'Certificados / constancias', true),
(441, 'Regular', 'Fojas y anexos', false),
(442, 'Regular', 'Fojas y anexos', true),
(443, 'Regular', 'Otorgamiento de crédito hipotecario', false),
(444, 'Regular', 'Otorgamiento de crédito hipotecario', false),
(446, 'Regular', 'Otorgamiento de crédito hipotecario', true),
(447, 'Regular', 'Acto/contrato traslativo de dominio', false),
(448, 'Regular', 'Acto/contrato traslativo de dominio', false),
(451, 'Regular', 'Anotaciones / rectificación', false),
(455, 'Regular', 'Fojas y anexos', false),
(456, 'Regular', 'Fojas y anexos', false),
(458, 'Regular', 'Certificados / constancias', false),
(459, 'Regular', 'Certificados / constancias', false),
(460, 'Regular', 'Certificados / constancias', false),
(461, 'Regular', 'Anotaciones / rectificación', false),
(462, 'Regular', 'Anotaciones / rectificación', false),
(463, 'Regular', 'Acto/contrato traslativo de dominio', true),
(464, 'Regular', 'Acto/contrato traslativo de dominio', true),
(467, 'Regular', 'Anotaciones / rectificación', true),
(471, 'Regular', 'Anotaciones / rectificación', true),
(472, 'Regular', 'Fojas y anexos', true),
(475, 'Regular', 'Certificados / constancias', true),
(477, 'Regular', 'Anotaciones / rectificación', true),
(478, 'Regular', 'Anotaciones / rectificación', true),
(480, 'Regular', 'Fojas y anexos', false),
(483, 'Regular', 'Certificados / constancias', false),
(484, 'Regular', 'Certificados / constancias', true),
(487, 'Regular', 'Aviso preventivo', false),
(488, 'Regular', 'Aviso preventivo', false),
(491, 'Regular', 'Aviso preventivo', true),
(493, 'INFONAVIT/FOVISSSTE', 'Acto/contrato traslativo de dominio', false),
(494, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(495, 'INFONAVIT/FOVISSSTE', 'Cancelación de crédito hipotecario', false),
(496, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(497, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(498, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(499, 'INFONAVIT/FOVISSSTE', 'Acto/contrato traslativo de dominio', false),
(500, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(501, 'INFONAVIT/FOVISSSTE', 'Cancelación de crédito hipotecario', false),
(502, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(503, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(504, 'INFONAVIT/FOVISSSTE', 'Otorgamiento de crédito hipotecario', false),
(505, 'Regular', 'Acto/contrato traslativo de dominio', false),
(506, 'Regular', 'Acto/contrato traslativo de dominio', false),
(509, 'Regular', 'Anotaciones / rectificación', false),
(513, 'Regular', 'Fojas y anexos', false),
(514, 'Regular', 'Fojas y anexos', false),
(517, 'Regular', 'Certificados / constancias', false),
(519, 'Regular', 'Anotaciones / rectificación', false),
(520, 'Regular', 'Anotaciones / rectificación', false),
(523, 'Regular', 'Aviso preventivo', false),
(535, 'INSUS', 'Acto/contrato traslativo de dominio', false),
(536, 'INSUS', 'Cancelación de reserva de dominio', false),
(537, 'INSUS', 'Subdivisión / fusión de predios', false),
(538, 'INSUS', 'Fojas y anexos', false),
(539, 'INSUS', 'Certificados / constancias', false),
(541, 'AGEPROO', 'Análisis y calificación', false),
(542, 'AGEPROO', 'Análisis y calificación', false),
(545, 'AGEPROO', 'Análisis y calificación', false),
(547, 'INSUS', 'Apeo y deslinde', false),
(548, 'INSUS', 'Apeo y deslinde', true),
(549, 'INSUS', 'Apeo y deslinde', false),
(558, 'INSUS', 'Análisis y calificación', false),
(559, 'INSUS', 'Análisis y calificación', true),
(564, 'INSUS', 'Fojas y anexos', false),
(565, 'INSUS', 'Fojas y anexos', true),
(574, 'Regular', 'Certificados / constancias', false),
(576, 'Regular', 'Análisis y calificación', false),
(577, 'Regular', 'Análisis y calificación', false),
(578, 'Regular', 'Análisis y calificación', false),
(579, 'Regular', 'Análisis y calificación', false),
(581, 'Regular', 'Análisis y calificación', false),
(586, 'Regular', 'Aviso preventivo', false),
(587, 'Regular', 'Aviso preventivo', false),
(588, 'Regular', 'Aviso preventivo', false),
(589, 'Regular', 'Aviso preventivo', false),
(591, 'Regular', 'Certificados / constancias', false),
(596, 'Regular', 'Certificados / constancias', false),
(597, 'Regular', 'Certificados / constancias', false),
(598, 'Regular', 'Certificados / constancias', false),
(599, 'Regular', 'Certificados / constancias', false),
(601, 'Regular', 'Análisis y calificación', false),
(604, 'Regular', 'Análisis y calificación', false),
(626, 'Regular', 'Cancelación de aviso preventivo', false),
(631, 'Regular', 'Análisis y calificación', true),
(632, 'Regular', 'Análisis y calificación', true),
(633, 'Regular', 'Análisis y calificación', true),
(634, 'Regular', 'Análisis y calificación', true),
(636, 'Regular', 'Análisis y calificación', true),
(641, 'Regular', 'Aviso preventivo', true),
(642, 'Regular', 'Aviso preventivo', true),
(643, 'Regular', 'Aviso preventivo', true),
(644, 'Regular', 'Aviso preventivo', true),
(651, 'Regular', 'Certificados / constancias', true),
(652, 'Regular', 'Certificados / constancias', true),
(653, 'Regular', 'Certificados / constancias', true),
(654, 'Regular', 'Certificados / constancias', true),
(656, 'Regular', 'Análisis y calificación', true),
(659, 'Regular', 'Análisis y calificación', true),
(681, 'Regular', 'Cancelación de aviso preventivo', true),
(687, 'Regular', 'Certificados / constancias', false),
(688, 'Regular', 'Certificados / constancias', false),
(691, 'Regular', 'Certificados / constancias', true),
(692, 'Regular', 'Certificados / constancias', true),
(696, 'Vivienda Bienestar', 'Sin clasificar', false),
(697, 'Vivienda Bienestar', 'Sin clasificar', true),
(698, 'INFONAVIT/FOVISSSTE', 'Aviso preventivo', false),
(699, 'INFONAVIT/FOVISSSTE', 'Aviso preventivo', true),
(702, 'INFONAVIT/FOVISSSTE', 'Certificados / constancias', false),
(703, 'INFONAVIT/FOVISSSTE', 'Certificados / constancias', true),
(704, 'Vivienda Bienestar', 'Certificados / constancias', false),
(705, 'Vivienda Bienestar', 'Certificados / constancias', true),
(706, 'INFONAVIT/FOVISSSTE', 'Anotaciones / rectificación', false),
(707, 'INFONAVIT/FOVISSSTE', 'Anotaciones / rectificación', true),
(708, 'Vivienda Bienestar', 'Anotaciones / rectificación', false),
(709, 'Vivienda Bienestar', 'Anotaciones / rectificación', true),
(712, 'Vivienda Bienestar', 'Fojas y anexos', false),
(713, 'Vivienda Bienestar', 'Fojas y anexos', true),
(714, 'Regular', 'Certificados / constancias', false),
(715, 'Regular', 'Análisis y calificación', false),
(725, 'Regular', 'Análisis y calificación', false),
(727, 'Regular', 'Fojas y anexos', false),
(728, 'Regular', 'Fojas y anexos', true),
(734, 'Regular', 'Certificados / constancias', false),
(735, 'Regular', 'Certificados / constancias', true),
(738, 'Regular', 'Análisis y calificación', false),
(739, 'Regular', 'Análisis y calificación', false),
(742, 'Regular', 'Certificados / constancias', false),
(743, 'Regular', 'Certificados / constancias', false),
(745, 'Regular', 'Anotaciones / rectificación', false),
(746, 'Regular', 'Cancelación de reserva de dominio', false),
(750, 'Regular', 'Análisis y calificación', true),
(751, 'Regular', 'Análisis y calificación', true),
(759, 'Regular', 'Cancelación de reserva de dominio', true);

-- Vista de ingresos SATQ enriquecida con el catálogo + bandera de conciliación con RPP.
DROP VIEW IF EXISTS vw_satq_conciliacion;
CREATE VIEW vw_satq_conciliacion AS
SELECT
  i.id, i.referencia, i.no_operacion, i.fecha_contable, i.municipio,
  i.id_concepto, i.concepto, i.importe, i.total_referencia,
  COALESCE(c.programa, 'Regular')         AS programa,
  COALESCE(c.tipo_acto, 'Sin clasificar') AS tipo_acto,
  COALESCE(c.es_subsidio, false)          AS es_subsidio,
  EXISTS (
    SELECT 1 FROM satq_lineas_captura l WHERE l.nolineacaptura = i.referencia
  ) AS conciliado
FROM satq_ingresos i
LEFT JOIN satq_catalogo_conceptos c ON c.id_concepto = i.id_concepto;
